# -*- coding: utf-8 -*-
"""AI Image Caption Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10GEwj3eXF73DUY2U7wQey4_T_VXri1ig
"""

!pip install -q transformers gradio Pillow

from transformers import BlipProcessor, BlipForConditionalGeneration
from PIL import Image

processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")

def generate_caption(image):
    image = image.convert("RGB")
    inputs = processor(images=image, return_tensors="pt")
    output = model.generate(**inputs)
    caption = processor.decode(output[0], skip_special_tokens=True)
    return caption

import gradio as gr

def caption_interface(image):
    return generate_caption(image)

demo = gr.Interface(
    fn=caption_interface,
    inputs=gr.Image(type="pil"),
    outputs="text",
    title="AI Image Caption Generator",
    description="Upload an image and get a descriptive caption generated using the BLIP model."
)

demo.launch(share=True)